### ISSUE TITLE
Call fails because it tries to use too many sql parameters

### ISSUE THREAD

**Issue by MatteoPiovanelli** [LaserSrl/Laser.Orchard.Platform#13]
https://github.com/LaserSrl/Laser.Orchard.Platform/blob/08e724f56f406029cbb0ecd04fbc1042cb24f403/src/Modules/Laser.Orchard.NwazetIntegration/Drivers/ShippingCountriesTerritoryPartDriver.cs#L35

The call from that line fails if there are more than 2100 territories in the hierarchy.

@ElenaRepository

**Comment by ElenaRepository** [comment]
it is still slow but now it opens
